// Pont réseau « réel » pour le Pico W simulé (option « Pont réseau réel via
// l'hôte » du todo). La puce Wi-Fi (CYW43439) n'est pas émulée par rp2040js :
// on fournit donc, côté MicroPython, de fausses implémentations de `network` et
// `urequests`/`requests` qui TUNNELLENT les requêtes HTTP vers l'hôte VS Code
// (Node `fetch`) via la liaison série, puis renvoient la vraie réponse au script.
//
// Protocole (sur l'USB-CDC, même principe que les séquences \x1bKX du débogage) :
//   script → hôte : « \x1bNT{json}\n »  (json = { id, m, url, headers?, body? })
//   hôte → script : « \x1bNR{json}\n »  (json = { id, status, body, reason?, error? })
// Le moteur Pico (pico.mts) filtre « \x1bNT… » de la sortie, relaie à l'hôte, et
// réinjecte « \x1bNR… » dans stdin du script. Le shim lit stdin en bloquant
// jusqu'à recevoir la réponse à l'identifiant courant (les autres octets de
// contrôle éventuels — commandes de débogage — sont ignorés pendant l'appel).
//
// Noms préfixés « __kxn » : exclus du panneau Variables (préfixe « _ »).

/** Préambule Python injecté en tête du script quand la carte est un Pico W. */
export const NET_PREAMBLE: string =
  [
    '# --- Kablix : pont reseau Pico W (injecte automatiquement) ---',
    'import sys as __kxn_sys',
    'import json as __kxn_json',
    '__kxn_id = 0',
    'def __kxn_call(__req):',
    '    global __kxn_id',
    '    __kxn_id += 1',
    "    __req['id'] = __kxn_id",
    "    __kxn_sys.stdout.write('\\x1bNT' + __kxn_json.dumps(__req) + '\\n')",
    '    __st = 0',  // 0=cherche ESC, 1=lit le tag, 2=lit le corps JSON
    "    __pre = ''",
    "    __buf = ''",
    '    while True:',
    '        __c = __kxn_sys.stdin.read(1)',
    '        if __st == 0:',
    "            if __c == '\\x1b':",
    '                __st = 1',
    "                __pre = ''",
    '            continue',
    '        if __st == 1:',
    '            __pre += __c',
    "            if __pre == 'NR':",
    '                __st = 2',
    "                __buf = ''",
    '            elif len(__pre) >= 2:',
    '                __st = 0',
    '            continue',
    "        if __c == '\\n':",
    '            try:',
    '                return __kxn_json.loads(__buf)',
    '            except Exception:',
    "                return {'error': 'bad response'}",
    '        else:',
    '            __buf += __c',
    'class __KxnResponse:',
    '    def __init__(self, __d):',
    "        self.status_code = __d.get('status', 0)",
    "        self.reason = __d.get('reason', '')",
    "        self._t = __d.get('body', '')",
    '    @property',
    '    def text(self):',
    '        return self._t',
    '    @property',
    '    def content(self):',
    '        return self._t.encode()',
    '    def json(self):',
    '        return __kxn_json.loads(self._t)',
    '    def close(self):',
    '        pass',
    'def __kxn_request(__method, __url, data=None, json=None, headers=None):',
    "    __req = {'m': __method, 'url': __url}",
    '    if headers:',
    "        __req['headers'] = headers",
    '    if json is not None:',
    "        __req['body'] = __kxn_json.dumps(json)",
    "        __h = __req.get('headers', {})",
    "        __h['Content-Type'] = 'application/json'",
    "        __req['headers'] = __h",
    '    elif data is not None:',
    "        __req['body'] = data if isinstance(data, str) else data.decode()",
    '    __d = __kxn_call(__req)',
    "    if __d.get('error'):",
    "        raise OSError(__d['error'])",
    '    return __KxnResponse(__d)',
    'class __KxnRequests:',
    '    def request(self, m, url, **kw):',
    '        return __kxn_request(m, url, **kw)',
    '    def get(self, url, **kw):',
    "        return __kxn_request('GET', url, **kw)",
    '    def post(self, url, **kw):',
    "        return __kxn_request('POST', url, **kw)",
    '    def put(self, url, **kw):',
    "        return __kxn_request('PUT', url, **kw)",
    '    def patch(self, url, **kw):',
    "        return __kxn_request('PATCH', url, **kw)",
    '    def delete(self, url, **kw):',
    "        return __kxn_request('DELETE', url, **kw)",
    '    def head(self, url, **kw):',
    "        return __kxn_request('HEAD', url, **kw)",
    'class __KxnWLAN:',
    '    def __init__(self, *a, **kw):',
    '        self._active = False',
    '        self._conn = False',
    '    def active(self, v=None):',
    '        if v is None:',
    '            return self._active',
    '        self._active = bool(v)',
    '        return self._active',
    '    def connect(self, *a, **kw):',
    '        self._conn = True',
    '    def disconnect(self):',
    '        self._conn = False',
    '    def isconnected(self):',
    '        return self._conn',
    '    def status(self, *a):',
    '        return 3 if self._conn else 0',  // 3 = STAT_GOT_IP
    '    def ifconfig(self, *a):',
    "        return ('192.168.1.50', '255.255.255.0', '192.168.1.1', '8.8.8.8')",
    '    def config(self, *a, **kw):',
    "        return 'kablix'",
    'class __KxnNetwork:',
    '    STA_IF = 0',
    '    AP_IF = 1',
    '    STAT_GOT_IP = 3',
    '    STAT_CONNECTING = 1',
    '    WLAN = __KxnWLAN',
    "__kxn_sys.modules['network'] = __KxnNetwork()",
    "__kxn_sys.modules['urequests'] = __KxnRequests()",
    "__kxn_sys.modules['requests'] = __kxn_sys.modules['urequests']",
    '# --- fin pont reseau Kablix ---',
  ].join('\n');
