// Pont réseau « réel » pour le Pico W simulé (option « Pont réseau réel via
// l'hôte » du todo). La puce Wi-Fi (CYW43439) n'est pas émulée par rp2040js :
// on fournit donc, côté MicroPython, de fausses implémentations de `network` et
// `urequests`/`requests` qui TUNNELLENT les requêtes HTTP vers l'hôte VS Code
// (Node `fetch`) via la liaison série, puis renvoient la vraie réponse au script.
//
// Protocole (sur l'USB-CDC, même principe que les séquences \x1bKX du débogage) :
//   script → hôte : « \x1bNT{json}\n »  (json = { id, m, url, headers?, body? })
//   hôte → script : « \x1bNR{json}\n »  (json = { id, status, body, reason?, error? })
// Le moteur Pico (pico.mts) filtre « \x1bNT… » de la sortie, relaie à l'hôte, et
// réinjecte « \x1bNR… » dans stdin du script. Le shim lit stdin en bloquant
// jusqu'à recevoir la réponse à l'identifiant courant (les autres octets de
// contrôle éventuels — commandes de débogage — sont ignorés pendant l'appel).
//
// Noms préfixés « _kxn » : exclus du panneau Variables (préfixe « _ »).

/** Préambule Python injecté en tête du script quand la carte est un Pico W. */
export const NET_PREAMBLE: string =
  [
    '# --- Kablix : pont reseau Pico W (injecte automatiquement) ---',
    'import sys as _kxn_sys',
    'import json as _kxn_json',
    'import binascii as _kxn_ba',
    '_kxn_id = 0',
    // __kx_net_wait : le preambule de debogage (pydebug.ts) sonde stdin
    // toutes les 50 ms et jette ce qu'il ne reconnait pas. Deux lecteurs pour
    // le meme flux, donc une reponse reseau sur deux disparaissait. Le drapeau
    // fait taire la sonde tant qu'un appel attend la sienne ; hors debogage,
    // ce n'est qu'une globale de plus, que personne ne lit.
    'def _kxn_call(_req):',
    '    global _kxn_id, __kx_net_wait',
    '    _kxn_id += 1',
    "    _req['id'] = _kxn_id",
    '    __kx_net_wait = True',
    '    try:',
    "        _kxn_sys.stdout.write('\\x1bNT' + _kxn_json.dumps(_req) + '\\n')",
    '        _st = 0',  // 0=cherche ESC, 1=lit le tag, 2=lit le corps JSON
    "        _pre = ''",
    "        _buf = ''",
    '        while True:',
    '            _c = _kxn_sys.stdin.read(1)',
    '            if _st == 0:',
    "                if _c == '\\x1b':",
    '                    _st = 1',
    "                    _pre = ''",
    '                continue',
    '            if _st == 1:',
    '                _pre += _c',
    "                if _pre == 'NR':",
    '                    _st = 2',
    "                    _buf = ''",
    '                elif len(_pre) >= 2:',
    '                    _st = 0',
    '                continue',
    "            if _c == '\\n':",
    '                try:',
    '                    return _kxn_json.loads(_buf)',
    '                except Exception:',
    "                    return {'error': 'bad response'}",
    '            else:',
    '                _buf += _c',
    '    finally:',
    '        __kx_net_wait = False',
    'class _KxnResponse:',
    '    def __init__(self, _d):',
    "        self.status_code = _d.get('status', 0)",
    "        self.reason = _d.get('reason', '')",
    "        self._t = _d.get('body', '')",
    '    @property',
    '    def text(self):',
    '        return self._t',
    '    @property',
    '    def content(self):',
    '        return self._t.encode()',
    '    def json(self):',
    '        return _kxn_json.loads(self._t)',
    '    def close(self):',
    '        pass',
    'def _kxn_request(_method, _url, data=None, json=None, headers=None):',
    "    _req = {'m': _method, 'url': _url}",
    '    if headers:',
    "        _req['headers'] = headers",
    '    if json is not None:',
    "        _req['body'] = _kxn_json.dumps(json)",
    "        _h = _req.get('headers', {})",
    "        _h['Content-Type'] = 'application/json'",
    "        _req['headers'] = _h",
    '    elif data is not None:',
    "        _req['body'] = data if isinstance(data, str) else data.decode()",
    '    _d = _kxn_call(_req)',
    "    if _d.get('error'):",
    "        raise OSError(_d['error'])",
    '    return _KxnResponse(_d)',
    'class _KxnRequests:',
    '    def request(self, m, url, **kw):',
    '        return _kxn_request(m, url, **kw)',
    '    def get(self, url, **kw):',
    "        return _kxn_request('GET', url, **kw)",
    '    def post(self, url, **kw):',
    "        return _kxn_request('POST', url, **kw)",
    '    def put(self, url, **kw):',
    "        return _kxn_request('PUT', url, **kw)",
    '    def patch(self, url, **kw):',
    "        return _kxn_request('PATCH', url, **kw)",
    '    def delete(self, url, **kw):',
    "        return _kxn_request('DELETE', url, **kw)",
    '    def head(self, url, **kw):',
    "        return _kxn_request('HEAD', url, **kw)",
    'class _KxnWLAN:',
    '    def __init__(self, *a, **kw):',
    '        self._active = False',
    '        self._conn = False',
    // AP_IF (1) : le script se veut point d'accès. Il n'y en a pas — c'est
    // l'hôte qui tiendra la prise TCP, sur le réseau de la MACHINE.
    '        self._ap = bool(a) and a[0] == 1',
    "        self._cfg = {'essid': 'kablix', 'ssid': 'kablix', 'channel': 1}",
    '    def active(self, v=None):',
    '        if v is None:',
    '            return self._active',
    '        self._active = bool(v)',
    '        return self._active',
    '    def connect(self, *a, **kw):',
    '        self._conn = True',
    '    def disconnect(self):',
    '        self._conn = False',
    '    def isconnected(self):',
    '        return self._conn',
    '    def status(self, *a):',
    // En point d'accès, `status()` compte les stations associées : on n'en sait
    // rien (le client parle à l'hôte, pas au script) — 1 dit « quelqu'un peut
    // venir » sans prétendre le compter.
    '        if self._ap:',
    '            return 1 if self._active else 0',
    '        return 3 if self._conn else 0',  // 3 = STAT_GOT_IP
    '    def ifconfig(self, *a):',
    '        if a:',
    '            return None',
    "        _ip = '192.168.1.50'",
    '        if self._ap:',
    // La vraie adresse de la machine, pas le 192.168.4.1 d'un point d'accès
    // Pico : c'est celle-là que le téléphone doit viser.
    "            _r = _kxn_call({'op': 'apinfo'})",
    "            _ip = _r.get('ip') or _ip",
    "        return (_ip, '255.255.255.0', _ip, '8.8.8.8')",
    '    def config(self, *a, **kw):',
    '        if kw:',
    '            self._cfg.update(kw)',
    '            return None',
    '        if a:',
    "            if a[0] in ('essid', 'ssid'):",
    "                return self._cfg.get('essid', 'kablix')",
    "            if a[0] == 'mac':",
    "                return b'\\x28\\xcd\\xc1\\x00\\x00\\x01'",
    '            return self._cfg.get(a[0], 0)',
    "        return 'kablix'",
    'class _KxnNetwork:',
    '    STA_IF = 0',
    '    AP_IF = 1',
    '    STAT_GOT_IP = 3',
    '    STAT_CONNECTING = 1',
    '    WLAN = _KxnWLAN',
    // --- Prises TCP : le script fait le serveur, l'hôte tient la vraie prise ---
    // Les octets voyagent en HEXADÉCIMAL : le tunnel est du texte JSON, et une
    // requête HTTP n'est pas garantie décodable en UTF-8.
    'def _kxn_hex(_b):',
    '    return _kxn_ba.hexlify(_b).decode()',
    'def _kxn_unhex(_s):',
    "    return _kxn_ba.unhexlify(_s) if _s else b''",
    'def _kxn_bytes(_d):',
    '    if isinstance(_d, str):',
    '        return _d.encode()',
    '    return bytes(_d)',
    'class _KxnConn:',
    '    def __init__(self, _cid, _data):',
    '        self._cid = _cid',
    '        self._buf = _data',
    '        self._closed = False',
    '    def recv(self, n=1024):',
    '        if not self._buf and not self._closed:',
    "            _r = _kxn_call({'op': 'recv', 'cid': self._cid, 'n': n})",
    "            self._buf = _kxn_unhex(_r.get('data', ''))",
    '        _b = self._buf[:n]',
    '        self._buf = self._buf[n:]',
    '        return _b',
    '    def read(self, n=1024):',
    '        return self.recv(n)',
    '    def readline(self):',
    "        _out = b''",
    '        while True:',
    '            _c = self.recv(1)',
    '            if not _c:',
    '                return _out',
    '            _out += _c',
    "            if _c == b'\\n':",
    '                return _out',
    '    def send(self, _d):',
    '        _b = _kxn_bytes(_d)',
    "        _kxn_call({'op': 'send', 'cid': self._cid, 'data': _kxn_hex(_b)})",
    '        return len(_b)',
    '    def sendall(self, _d):',
    '        return self.send(_d)',
    '    def write(self, _d):',
    '        return self.send(_d)',
    // makefile('rwb', 0) : le motif des tutos MicroPython. Le fichier EST la
    // prise (pas de tampon à gérer), donc on se rend soi-même.
    '    def makefile(self, *a, **kw):',
    '        return self',
    '    def close(self):',
    '        if not self._closed:',
    '            self._closed = True',
    "            _kxn_call({'op': 'close', 'cid': self._cid})",
    'class _KxnSocket:',
    '    def __init__(self, *a, **kw):',
    '        self._port = 80',
    '        self._listening = False',
    '    def setsockopt(self, *a):',
    '        return None',
    '    def settimeout(self, *a):',
    '        return None',
    '    def setblocking(self, *a):',
    '        return None',
    '    def bind(self, _addr):',
    '        try:',
    '            self._port = int(_addr[1])',
    '        except Exception:',
    '            self._port = 80',
    '    def listen(self, backlog=1):',
    "        _r = _kxn_call({'op': 'listen', 'port': self._port})",
    "        if _r.get('error'):",
    "            raise OSError(_r['error'])",
    '        self._listening = True',
    // Le port demandé n'est pas toujours celui obtenu (80 est souvent pris) :
    // on annonce l'adresse RÉELLE, sinon le téléphone frappe à une porte close.
    "        print('[Kablix] serveur du Pico W : http://%s:%d/ (a ouvrir depuis"
      + " le telephone, sur le meme reseau)' % (_r.get('ip', '?'),"
      + " _r.get('port', self._port)))",
    '    def accept(self):',
    "        _r = _kxn_call({'op': 'accept'})",
    "        if _r.get('error'):",
    "            raise OSError(_r['error'])",
    "        _c = _KxnConn(_r.get('cid', 0), _kxn_unhex(_r.get('data', '')))",
    "        return (_c, (_r.get('peer', '0.0.0.0'), 0))",
    '    def close(self):',
    '        if self._listening:',
    '            self._listening = False',
    "            _kxn_call({'op': 'unlisten'})",
    'class _KxnSocketMod:',
    '    AF_INET = 2',
    '    SOCK_STREAM = 1',
    '    SOL_SOCKET = 1',
    '    SO_REUSEADDR = 2',
    '    socket = _KxnSocket',
    '    error = OSError',
    '    def getaddrinfo(self, _host, _port, *a):',
    "        return [(2, 1, 0, '', (_host, _port))]",
    "_kxn_sys.modules['network'] = _KxnNetwork()",
    "_kxn_sys.modules['urequests'] = _KxnRequests()",
    "_kxn_sys.modules['requests'] = _kxn_sys.modules['urequests']",
    "_kxn_sys.modules['socket'] = _KxnSocketMod()",
    "_kxn_sys.modules['usocket'] = _kxn_sys.modules['socket']",
    '# --- fin pont reseau Kablix ---',
  ].join('\n');
